name: Заявка на участие в Хакатоне
description: Подайте заявку, если хотите приехать на Хакатон в Москве
title: <Тема вашего проекта>
labels: [На рассмотрении]
body:
- type: checkboxes
  id: captain
  attributes:
    label: Вы капитан команды?
    description: Подать заявку может только капитан команды. Капитан принимает все решения в команде, добавляет и исключает участников, представляет проект
    options:
    - label: Да, я капитан команды
      required: true
- type: checkboxes
  id: offline
  attributes:
    label: Вы готовы приехать на Хакатон в Москву?
    description: Все участники должны присутствовать в месте проведения 3-5 декабря
    options:
    - label: Да, команда будет на месте
      required: true
- type: textarea
  id: idea
  attributes:
    label: Подробно опишите идею вашего проекта
    description: Какую задачу решает ваш проект? Какие технологии Флиппера хотите задействовать? Претендуете ли на включение вашего кода в основную прошивку?
    placeholder: |
      Хотел бы сделать мультиплеерную игру для нескольких Флипперов (через приёмопередатчик 433 МГц), 3Д-экшон суть такова...
      Пользователь может играть большими роботами, ангелами и злодеем.
      И если пользователь играет роботами то, набигают ангелы и сверлят моск.
      Потом все превращаются в желтый суп...
      P.S. Я джва года хочу такую игру.
  validations:
    required: true
- type: textarea
  id: result
  attributes:
    label: Готовый проект будет уметь...
    description: Чётко сформулируйте критерий успешного выполнения проекта. Соответствие ему будет считаться победой
    placeholder: |
      В моей игре будет 26 уровней и 5 боссов. Будет возможность играть онлайн с другими владельцами Флиппера через 433 МГц и передавать друг другу игровые предметы из инвентаря.
  validations:
    required: true
- type: input
  id: second-member
  attributes:
    label: GitHub второго участника
    description: Не заполняйте, если вы единственный участник
    placeholder: '@shinji'
- type: input
  id: third-member
  attributes:
    label: GitHub третьего участника
    description: Не заполняйте, если в команде 1-2 человека
    placeholder: '@asuka'
